### ISSUE TITLE
Benchmarks TODO

### ISSUE THREAD

**Issue by mratsim** [mratsim/weave#2]
### Important benchmarks

- [ ] Framework overhead via fibonacci
- [ ] Unbalanced Tree Search
- [ ] GEMM / Matrix Multiply vs OpenBLAS and MKL
- [ ] Binary size overhead when runtime is not compiled in
- [ ] Space overhead at runtime vs serial code
- [ ] Returning memory to the OS on long-running processes

### Instrumentation, tutorials, examples

- [ ] bloaty for binary size
- [ ] measuring cache misses
- [ ] measuring cache contention / false sharing via `perf c2c`
- [ ] `coz` for causal profiling and bottleneck detection

### Stretch goals
- [ ] Other common benchmarks (nqueens, nbodies, LU, heat, qsort, bouncing producer-consumer, ...)
- [ ] Porting michi (550 lines go bot with parallel Monte-Carlo Tree Search in Python) to Nim (https://github.com/pasky/michi)
